# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(828, 498)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.CameraButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CameraButton.setFont(font)
        self.CameraButton.setObjectName("CameraButton")
        self.verticalLayout.addWidget(self.CameraButton)
        self.CameraCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CameraCheckBox.setFont(font)
        self.CameraCheckBox.setTristate(False)
        self.CameraCheckBox.setObjectName("CameraCheckBox")
        self.verticalLayout.addWidget(self.CameraCheckBox, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tolerancelabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tolerancelabel.sizePolicy().hasHeightForWidth())
        self.tolerancelabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tolerancelabel.setFont(font)
        self.tolerancelabel.setObjectName("tolerancelabel")
        self.horizontalLayout_2.addWidget(self.tolerancelabel)
        self.toleranceSlider = QtWidgets.QSlider(self.centralwidget)
        self.toleranceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.toleranceSlider.setObjectName("toleranceSlider")
        self.horizontalLayout_2.addWidget(self.toleranceSlider)
        self.valueLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.valueLabel.setFont(font)
        self.valueLabel.setObjectName("valueLabel")
        self.horizontalLayout_2.addWidget(self.valueLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.upsampleLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upsampleLabel.sizePolicy().hasHeightForWidth())
        self.upsampleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.upsampleLabel.setFont(font)
        self.upsampleLabel.setObjectName("upsampleLabel")
        self.horizontalLayout_3.addWidget(self.upsampleLabel)
        self.radioButton1 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton1.setFont(font)
        self.radioButton1.setObjectName("radioButton1")
        self.horizontalLayout_3.addWidget(self.radioButton1)
        self.radioButton2 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton2.setFont(font)
        self.radioButton2.setObjectName("radioButton2")
        self.horizontalLayout_3.addWidget(self.radioButton2)
        self.radioButton4 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton4.setFont(font)
        self.radioButton4.setObjectName("radioButton4")
        self.horizontalLayout_3.addWidget(self.radioButton4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.registerButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerButton.sizePolicy().hasHeightForWidth())
        self.registerButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.registerButton.setFont(font)
        self.registerButton.setObjectName("registerButton")
        self.gridLayout_2.addWidget(self.registerButton, 0, 0, 1, 1)
        self.loadOutButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadOutButton.sizePolicy().hasHeightForWidth())
        self.loadOutButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.loadOutButton.setFont(font)
        self.loadOutButton.setObjectName("loadOutButton")
        self.gridLayout_2.addWidget(self.loadOutButton, 1, 1, 1, 1)
        self.loadInButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadInButton.sizePolicy().hasHeightForWidth())
        self.loadInButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.loadInButton.setFont(font)
        self.loadInButton.setObjectName("loadInButton")
        self.gridLayout_2.addWidget(self.loadInButton, 1, 0, 1, 1)
        self.batchRegisterButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchRegisterButton.sizePolicy().hasHeightForWidth())
        self.batchRegisterButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.batchRegisterButton.setFont(font)
        self.batchRegisterButton.setObjectName("batchRegisterButton")
        self.gridLayout_2.addWidget(self.batchRegisterButton, 0, 1, 1, 1)
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.infoLabel.setFont(font)
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")
        self.gridLayout_2.addWidget(self.infoLabel, 2, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.nameBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.nameBrowser.setObjectName("nameBrowser")
        self.verticalLayout_3.addWidget(self.nameBrowser)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.FrameLabel = QtWidgets.QLabel(self.centralwidget)
        self.FrameLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.FrameLabel.sizePolicy().hasHeightForWidth())
        self.FrameLabel.setSizePolicy(sizePolicy)
        self.FrameLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.FrameLabel.setStyleSheet("background:black;")
        self.FrameLabel.setText("")
        self.FrameLabel.setScaledContents(False)
        self.FrameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FrameLabel.setOpenExternalLinks(False)
        self.FrameLabel.setObjectName("FrameLabel")
        self.horizontalLayout.addWidget(self.FrameLabel)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CameraButton.setText(_translate("MainWindow", "开启摄像头"))
        self.CameraCheckBox.setText(_translate("MainWindow", "外置相机"))
        self.tolerancelabel.setText(_translate("MainWindow", "容错率"))
        self.valueLabel.setText(_translate("MainWindow", "00"))
        self.upsampleLabel.setText(_translate("MainWindow", "上采样"))
        self.radioButton1.setText(_translate("MainWindow", "1"))
        self.radioButton2.setText(_translate("MainWindow", "2"))
        self.radioButton4.setText(_translate("MainWindow", "4"))
        self.registerButton.setText(_translate("MainWindow", "注册"))
        self.loadOutButton.setText(_translate("MainWindow", "导出"))
        self.loadInButton.setText(_translate("MainWindow", "导入"))
        self.batchRegisterButton.setText(_translate("MainWindow", "批量注册"))
        self.infoLabel.setText(_translate("MainWindow", "当前人员"))
